version: "3"

services:
  qgis:
    build: ./qgis
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./io/:/io/
      - qgis_share:/root/.local/share/QGIS
    privileged: true
    network_mode: host

volumes:
  qgis_share:
